


SCREEN_SIZE = (800,400)


SERVER_OUTPUT_PID = 41483
SERVER_PORT = 26008

JTAG_CHUNK_TYPE = "CTYPE"
JTAG_EVENT = "EVENT"

JTAG_SUCCESS = "SUCCESS"
JTAG_USERNAME = "USERNAME" # Perhaps replace with a general string argument?
JTAG_USER_ID = "USER_ID" # Perhaps replace with a general int argument?

JKEY_CHUNK_TYPE_EVENT = "EVENT"
JKEY_CHUNK_TYPE_JOIN_REQUEST = "JOIN_REQUEST"
JKEY_CHUNK_TYPE_JOIN_RESPONSE = "JOIN_RESPONSE"


JTAG_EVENT_TYPE = "ETYPE"
JTAG_EVENT_ORDER = "ORDER"
JTAG_EVENT_ARGUMENTS = "ARGS"

JTAG_EVENT_FLOAT2 = "FLOAT2" # Can refer to a list in practice
JTAG_EVENT_INT = "INT" # Can refer to a list in practice

JKEY_EVENT_TYPE_ADDPOSITION = "ADD_POSITION"


RADIUS_POSITION = 10
COLOR_BLACK = (0,0,0)
COLOR_GREEN = (255,0,0)